"""Add is_bone_mallow_donor field

Revision ID: 5e12a8ab6393
Revises: 138caa6b2ef5
Create Date: 2025-07-19 08:35:43.179676

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e12a8ab6393"
down_revision: str | None = "138caa6b2ef5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_donations_donor_day_id_donor_days"), "donations", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_donations_donor_day_id_donor_days"),
        "donations",
        "donor_days",
        ["donor_day_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("donors", sa.Column("is_bone_marrow_donor", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("donors", "is_bone_marrow_donor")
    op.drop_constraint(op.f("fk_donations_donor_day_id_donor_days"), "donations", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_donations_donor_day_id_donor_days"), "donations", "donor_days", ["donor_day_id"], ["id"]
    )
    # ### end Alembic commands ###
