"""Add telegram_id field

Revision ID: 138caa6b2ef5
Revises: 6c3bfcd82630
Create Date: 2025-07-19 02:20:45.012694

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "138caa6b2ef5"
down_revision: str | None = "6c3bfcd82630"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("donors", sa.Column("telegram_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("donors", "telegram_id")
    # ### end Alembic commands ###
