"""Add content model

Revision ID: 18a5a030af58
Revises: 5e12a8ab6393
Create Date: 2025-07-19 11:52:22.737941

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18a5a030af58"
down_revision: str | None = "5e12a8ab6393"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("organizer_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organizer_id"], ["organizers.id"], name=op.f("fk_content_organizer_id_organizers")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content")),
    )
    op.create_index(op.f("ix_content_id"), "content", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_content_id"), table_name="content")
    op.drop_table("content")
    # ### end Alembic commands ###
